#!/bin/bash

text_color=`tput setaf 2`
reset=`tput sgr0`

echo -e "${text_color}Let's setup a Django REST environment!${reset}"

echo -e "\n${text_color}Create requirements.txt and install dependencies${reset}"

echo "django
djangorestframework
django-filter" >> requirements.txt

pip install -r requirements.txt

# .gitignore
# https://github.com/django/django/blob/master/.gitignore
echo -e "\n${text_color}Add Django specific ignore rules to .gitignore${reset}"

echo "*.egg-info
*.pot
*.py[co]
.tox/
__pycache__
MANIFEST
dist/
docs/_build/
docs/locale/
node_modules/
tests/coverage_html/
tests/.coverage
build/
tests/report/" >> .gitignore

# README.md
echo -e "\n${text_color}Generate a simple README.md file${reset}"

echo "# Project Name

## Requirements

* Python 3.7+" > README.md

# Setup Django
# https://docs.djangoproject.com/

echo -e "\n${text_color}Start project: app${reset}"
django-admin startproject app .

echo -e "\n${text_color}Migrate${reset}"
python manage.py migrate

echo -e "\n${text_color}Create super user${reset}"
python manage.py createsuperuser

# Check to see everything is good
echo -e "\n${text_color}Check to see everything is good${reset}"
python manage.py check

# Setup Instruction
echo -e "\n${text_color}Don't forget to setup Django REST Framework: http://www.django-rest-framework.org/"
