#!/bin/bash

text_color=`tput setaf 2`
reset=`tput sgr0`

echo -e "${text_color}Let's setup a Django REST environment!${reset}"

echo -e "\n${text_color}Create requirements.txt and install dependencies${reset}"

echo "django
djangorestframework
django-filter" >> requirements.txt

pip install -r requirements.txt

# .gitignore
# https://github.com/django/django/blob/master/.gitignore
echo -e "\n${text_color}Add Django specific ignore rules to .gitignore${reset}"

echo "*.egg-info
*.pot
*.py[co]
.tox/
__pycache__
MANIFEST
dist/
docs/_build/
docs/locale/
node_modules/
tests/coverage_html/
tests/.coverage
build/
tests/report/" >> .gitignore

# README.md
echo -e "\n${text_color}Generate a simple README.md file${reset}"

echo "# Project Name

## Requirements

* Python 3.7+" > README.md

# Setup Django
# https://docs.djangoproject.com/

echo -e "\n${text_color}Start project: app${reset}"
django-admin startproject app .

# Check to see if everything looks good
echo -e "\n${text_color}Check to see if everything looks good${reset}"
python manage.py check

# Setup Instruction
echo -e "\n${text_color}Hooray! Here are your next steps:${reset}
\nSetup your Database:
\tCreate Postgres DB: https://www.digitalocean.com/community/tutorials/how-to-use-postgresql-with-your-django-application-on-ubuntu-16-04#create-a-database-and-database-user
\tBootstrap Postgres in Django: https://stackoverflow.com/questions/5394331/how-to-setup-postgresql-database-in-django#answer-5421511
\nSetup Django REST Framework: http://www.django-rest-framework.org/"
