#!/bin/bash

text_color=`tput setaf 2`
reset=`tput sgr0`

echo -e "${text_color}Let's setup a Django environment!${reset}"

echo -e "\n${text_color}Create requirements.txt and install dependencies${reset}"

echo "django
djangorestframework
django-filter" >> requirements.txt

pip install -r requirements.txt

# .gitignore
# https://github.com/django/django/blob/master/.gitignore
echo -e "${text_color}Add Django specific ignore rules to .gitignore${reset}"

echo "*.egg-info
*.pot
*.py[co]
.tox/
__pycache__
MANIFEST
dist/
docs/_build/
docs/locale/
node_modules/
tests/coverage_html/
tests/.coverage
build/
tests/report/" >> .gitignore

# Setup Django
# https://docs.djangoproject.com/

echo -e "\n${text_color}Start project: app${reset}"
django-admin startproject app

echo -e "\n${text_color}Migrate${reset}"
python app/manage.py migrate

echo -e "\n${text_color}Create super user${reset}"
python app/manage.py createsuperuser

# Setup Django REST Framework
# http://www.django-rest-framework.org/
echo -e "\n${text_color}Install Django REST Framework${reset}"

# Check to see everything is good
echo -e "\n${text_color}Check to see everything is good${reset}"
python app/manage.py check

# Start Server
echo -e "\n${text_color}Start Django server${reset}"
python app/manage.py runserver
